# Generated by Django 2.1.4 on 2018-12-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobj',
            name='guid',
            field=models.CharField(max_length=32),
        ),
    ]
