# Generated by Django 2.1.4 on 2018-12-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_python', '0002_auto_20181220_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageobj',
            name='guid',
        ),
        migrations.AddField(
            model_name='imageobj',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='test_python.TaskObj'),
        ),
    ]
