# Generated by Django 2.1.4 on 2018-12-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_python', '0003_auto_20181221_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobj',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_python.TaskObj'),
        ),
    ]
